version: '3.3'
services:
    flent-server:
        build:
            context: .
            dockerfile: Dockerfile.flent-server
        # Expose the netserver port on the host
        ports: 
            - "12865-12866:12865-12866/tcp"
            - "12865-12866:12865-12866/udp"
    flent-client:
        build:
            context: .
            dockerfile: Dockerfile.flent-client