version: '3.3'
services:
    perf-server:
        build:
            context: .
            dockerfile: Dockerfile.flent-server
        # Expose the netserver port on the host
        ports: 
            - "12865-12866:12865-12866/tcp"
            - "12865-12866:12865-12866/udp"
            - "2112:2112/tcp"
            - "2112:2112/udp"
    perf-client:
        build:
            context: .
            dockerfile: Dockerfile.flent-client