version: '3.3'
services:
    perf-server:
        build:
            context: .
            dockerfile: Dockerfile.perf-server
        image: untangle/netperf-server
        network_mode: host
        env_file:
            - .env
    perf-client:
        build:
            context: .
            dockerfile: Dockerfile.perf-client
        image: untangle/performance-test-client
        env_file:
            - .env
    perf-results-sshd:
        build:
            context: .
            dockerfile: Dockerfile.perf-results-sshd
        image: untangle/performance-results-sshd
        env_file:
            - .env
        # Expose Web service on 8080 and SSH on the RES_PORT
        ports:
            - "${RES_SSH_PORT}:22"
        volumes:
            - /data/performance-results:/data/
    perf-results-nginx:
        build:
            context: .
            dockerfile: Dockerfile.perf-results-nginx
        image: untangle/performance-results-nginx
        env_file:
            - .env
        # Expose Web service on 8080 and SSH on the RES_PORT
        ports:
            - "8080:80"
        volumes:
            - /data/performance-results:/data/
    perf-results-orchestrator:
        build:
            context: .
            dockerfile: Dockerfile.perf-orchestrator
        image: untangle/performance-results-orchestrator
        env_file:
            - .env
        # This container uses the local host docker sock and SSH keys
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.ssh/:/root/.ssh/